### ISSUE TITLE
预测FUNSD的模型

### ISSUE THREAD

**Issue by TyrionChou** [NormXU/Layout2Graph#10]
您好，非常感谢您的工作！有一个疑问想问一下，在使用FUNSD数据训练好的模型预测时报错：
![企业微信截图_16969952852751](https://github.com/NormXU/Layout2Graph/assets/25079938/af80ad7c-6888-4b40-87dc-a4d4e1809b8a)
我查看了预处理的json文件里面确实没有cells属性，是需要针对FUNSD按照layout_dataset.py的格式进行修改吗？

**Comment by NormXU** [comment]
@TyrionChou Yes. The prediction assumes that all datasets are in [this](https://github.com/DS4SD/DocLayNet#extra-json-files) format. I think you should preprocess the FUNSD dataset. I am not very good at reading Chinese, and I used chatGPT to help me understand the issue. If there is anything I misunderstand, please remind me.

**Comment by TyrionChou** [comment]
hi~, how to set hyper-parameters (1.node_weights 2.edge_weight) in config file.
I use my own dataset and i only have one class,just like text,
how i to set or i just process data according to the format.
thank you very much!

**Comment by NormXU** [comment]
@TyrionChou The weight of the node needs to be carefully adjusted to obtain a desirable outcome. Empirically, classes with fewer samples should be given a higher weight, and vice versa. For a single class, you might begin with a node weight of 1.0.

Regarding the edge_weight, it determines how positive or negative edges contribute to the final loss. If the negative edge (an edge formed by graph sampling but isn't a valid connection) is dominant, you may want to consider reducing its corresponding weight in edge_weight. A good choice is to use dynamic edge weight: For example, in one batch, you have 2 negative edges and 1 position edge, in order to avoid the negative edges dominating the loss, the negative edge weight can be $1 / (2 + 1)$ and positive edge weight is set to  $2 / (2 + 1)$

**Comment by yudezhi123456** [comment]
> 您好，非常感谢您的工作！有一个疑问想问一下，在使用FUNSD数据训练好的模型预测时报错： ![企业微信截图_16969952852751](https://user-images.githubusercontent.com/25079938/274133719-af80ad7c-6888-4b40-87dc-a4d4e1809b8a.png) 我查看了预处理的json文件里面确实没有cells属性，是需要针对FUNSD按照layout_dataset.py的格式进行修改吗？

想问一下，你预测出来的FUNSD是怎么样的，我的是这样的结果，对entity任务中的预测结果：{'accuracy_cls': 0.6852060002662849, 'Node_F1_MACRO': 0.7031320376981303, 'Node_F1_MICRO': 0.7894273127753304, 'sums_cls': 2270, 'correct_cls': 1792, 'accuracy_map_cls': {0: (925, 1070, 0.8644859813084113), 1: (638, 809, 0.788627935723115), 2: (52, 119, 0.4369747899159664), 3: (177, 272, 0.6507352941176471)}, 'accuracy_cell': 1.0, 'Pair_F1_MACRO': 1.0, 'Pair_F1_MICRO': 1.0, 'sums_cell': 6416, 'correct_cell': 6416, 'accuracy_map_cell': {0: (6416, 6416, 1.0)}})
发现entity-labeling和作者论文是差不多，但是entity-Linking到了1.0。想问一下，佬你预测出来是什么样的？

**Comment by TyrionChou** [comment]
> > 您好，非常感谢您的工作！有一个疑问想问一下，在使用FUNSD数据训练好的模型预测时报错： ![企业微信截图_16969952852751](https://user-images.githubusercontent.com/25079938/274133719-af80ad7c-6888-4b40-87dc-a4d4e1809b8a.png) 我查看了预处理的json文件里面确实没有cells属性，是需要针对FUNSD按照layout_dataset.py的格式进行修改吗？
> 
> 想问一下，你预测出来的FUNSD是怎么样的，我的是这样的结果，对entity任务中的预测结果：{'accuracy_cls': 0.6852060002662849, 'Node_F1_MACRO': 0.7031320376981303, 'Node_F1_MICRO': 0.7894273127753304, 'sums_cls': 2270, 'correct_cls': 1792, 'accuracy_map_cls': {0: (925, 1070, 0.8644859813084113), 1: (638, 809, 0.788627935723115), 2: (52, 119, 0.4369747899159664), 3: (177, 272, 0.6507352941176471)}, 'accuracy_cell': 1.0, 'Pair_F1_MACRO': 1.0, 'Pair_F1_MICRO': 1.0, 'sums_cell': 6416, 'correct_cell': 6416, 'accuracy_map_cell': {0: (6416, 6416, 1.0)}}) 发现entity-labeling和作者论文是差不多，但是entity-Linking到了1.0。想问一下，佬你预测出来是什么样的？

我没训练几轮，结果不是很高

**Comment by yudezhi123456** [comment]
好的好的，你也是在研究这个方向吗？我们可以讨论讨论，相互帮助




骑猪№兜风ㄘ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NormXU/Layout2Graph"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月13日(星期五) 下午4:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NormXU/Layout2Graph] 预测FUNSD的模型 (Issue #10)





   
您好，非常感谢您的工作！有一个疑问想问一下，在使用FUNSD数据训练好的模型预测时报错：  我查看了预处理的json文件里面确实没有cells属性，是需要针对FUNSD按照layout_dataset.py的格式进行修改吗？
  
想问一下，你预测出来的FUNSD是怎么样的，我的是这样的结果，对entity任务中的预测结果：{'accuracy_cls': 0.6852060002662849, 'Node_F1_MACRO': 0.7031320376981303, 'Node_F1_MICRO': 0.7894273127753304, 'sums_cls': 2270, 'correct_cls': 1792, 'accuracy_map_cls': {0: (925, 1070, 0.8644859813084113), 1: (638, 809, 0.788627935723115), 2: (52, 119, 0.4369747899159664), 3: (177, 272, 0.6507352941176471)}, 'accuracy_cell': 1.0, 'Pair_F1_MACRO': 1.0, 'Pair_F1_MICRO': 1.0, 'sums_cell': 6416, 'correct_cell': 6416, 'accuracy_map_cell': {0: (6416, 6416, 1.0)}}) 发现entity-labeling和作者论文是差不多，但是entity-Linking到了1.0。想问一下，佬你预测出来是什么样的？
  
我没训练几轮，结果不是很高
