### ISSUE TITLE
Graph sampling

### ISSUE THREAD

**Issue by yudezhi123456** [NormXU/Layout2Graph#12]
Excellent work! I was wondering if the graph sampling part mentioned in the paper was the part pointed to by my link below. I did not find the graph sampling technique related to the paper in the code, thank you for your answer.
 
https://github.com/NormXU/Layout2Graph/blob/0f410b468eda6e8d5b4c589615568b3cf9100763/networks/graph_net/graph_layout_net.py#L182

**Comment by NormXU** [comment]
@yudezhi123456 The graph sampling code is here：
https://github.com/NormXU/Layout2Graph/blob/0f410b468eda6e8d5b4c589615568b3cf9100763/networks/graph_net/graph_layout_net.py#L304-L318

We provide three ways to sample the graph: KNN, Beta-skeleton, and customized which is mainly based on prior knowledge and geometry information of bounding boxes.

**Comment by yudezhi123456** [comment]
Thank you for your prompt answer!
