### ISSUE TITLE
version to setup environment

### ISSUE THREAD

**Issue by tuongtranngoc** [NormXU/Layout2Graph#13]
Hi, I tried installing with 2 versions torch-2.0.1  and torch 1.12.1 but I faced lib errors and not easy to fix. Can you provide a stable version that you can run before?
thanks

**Comment by tuongtranngoc** [comment]
For torch-2.0.1
![Screenshot from 2023-10-24 21-50-26](https://github.com/NormXU/Layout2Graph/assets/42471216/21f6a28e-6430-417a-a6a1-f7c0d7d255e4)

**Comment by NormXU** [comment]
@tuongtranngoc The `torch-2.0.1` and `torch1.12.1` is a stable version that I developed with. Could you please paste the lib error message, let's see what I can figure out
