### ISSUE TITLE
Finetune

### ISSUE THREAD

**Issue by samakos** [NormXU/Layout2Graph#2]
Hello, I am currently working on your model (layout2graph) but I experience lot of problems to finetune the model on other datasets. Is anyone available to help? More specifically I get the following error, and do not understand how you prepared the data for each dataset.

---------------------------------------------------------------------------

----> 1 from experiment.gragh_layout_experiment import GraphLayoutExperiment

~/SageMaker/Layout2Graph/experiment/gragh_layout_experiment.py in <module>
     20 from experiment.base_experiment import BaseExperiment
     21 from metrics.meter import AverageMeter
---> 22 from mydatasets.gragh_net.table_dataset import graph_get_pad_transform, variety_cell, graph_get_resize_transform
     23 from post_process import get_post_processor
     24 

ModuleNotFoundError: No module named 'mydatasets.gragh_net.table_dataset'

**Comment by weishu27** [comment]
Sorry, I forgot uploading some .py file.Please pull project and try again.
Thanks for your comment.

**Comment by samakos** [comment]
@weishu27 hello again,
AssertionError: path not exist /open-dataset/OD-layout/FUNSD_word_graph_labels/training_data
I would like to ask you how you prepared the data for funsd and doclaynet datasets. Did you just download the datasets and you had the folders (images and annotations folders) as they are? or you followed a different structure?

**Comment by weishu27** [comment]
1.Just download public data;Simply move image and annotion separately to folder ‘images’ and 'annotations' .
Or change input_path definition in .py as another choice.
2. /open-dataset/OD-layout/FUNSD_word_graph_labels/training_data is a save path,you can define it as you want.

**Comment by samakos** [comment]
@weishu27  thank you for your prompt response. I solved the problem

However, I get the following error when running the training script.
 collate_fn = getattr(mydatasets, collate_fn_type)(batch_size=batch_size, **collate_fn_args)
AttributeError: module 'mydatasets' has no attribute 'GraphCollateFn'

Do you have any idea?

**Comment by weishu27** [comment]
> @weishu27 thank you for your prompt response. I solved the problem
> 
> However, I get the following error when running the training script. collate_fn = getattr(mydatasets, collate_fn_type)(batch_size=batch_size, **collate_fn_args) AttributeError: module 'mydatasets' has no attribute 'GraphCollateFn'
> 
> Do you have any idea?

It's my mistake and fix it just now.

**Comment by samakos** [comment]
hello, and thank you very much. However, the training script still doesn't run

 collate_fn = getattr(mydatasets, collate_fn_type)(batch_size=batch_size, **collate_fn_args)
  File "/home/ec2-user/SageMaker/Layout2Graph/mydatasets/gragh_net/graph_collate.py", line 20, in __init__
    self.cut_percent = kwargs['cut_percent']
KeyError: 'cut_percent'

**Comment by samakos** [comment]
@weishu27  
hello, and thank you very much. However, the training script still doesn't run

collate_fn = getattr(mydatasets, collate_fn_type)(batch_size=batch_size, **collate_fn_args)
File "/home/ec2-user/SageMaker/Layout2Graph/mydatasets/gragh_net/graph_collate.py", line 20, in init
self.cut_percent = kwargs['cut_percent']
KeyError: 'cut_percent'

**Comment by samakos** [comment]
@weishu27 in addition I tried to remove these 5 lines to check if it works and I got the following error

  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/munch/__init__.py", line 103, in __getattr__
    return object.__getattribute__(self, k)
AttributeError: 'Munch' object has no attribute 'quantization_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/munch/__init__.py", line 106, in __getattr__
    return self[k]
KeyError: 'quantization_type'

During handling of the above exception, another exception occurred:
 File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/munch/__init__.py", line 108, in __getattr__
    raise AttributeError(k)
AttributeError: quantization_type

**Comment by weishu27** [comment]
> 

*--* , Sorry,All these problems are because I didn't upload my newest code which is much different with history version.

**Comment by samakos** [comment]
hello again, I spent this week exploring the model. Very good work!! However I think that there is a problem. When using the model in DocLayNet I expected AP in the end but got F1 scores. As I can see in graph_layout_metrics.py you only have the F1 scores. Maybe is that the problem, or I do something wrong?


One more problem that I faced (but solved) is that the path of the label root: e.g FUNSD_word_graph_labels/training_data 
are not from the original dataset. First I used the script you have for data preprocessing, after using that I generated the folder word_graph_labels, and this folder was used for the model. Is it correct?

**Comment by weishu27** [comment]
> hello again, I spent this week exploring the model. Very good work!! However I think that there is a problem. When using the model in DocLayNet I expected AP in the end but got F1 scores. As I can see in graph_layout_metrics.py you only have the F1 scores. Maybe is that the problem, or I do something wrong?
> 
> One more problem that I faced (but solved) is that the path of the label root: e.g FUNSD_word_graph_labels/training_data are not from the original dataset. First I used the script you have for data preprocessing, after using that I generated the folder word_graph_labels, and this folder was used for the model. Is it correct?

1.After prediction, we get a coco format result json file, then I calculate AP use https://github.com/NormXU/Layout2Graph/blob/main/scripts/coco_evaluate.py#L38  
2. Yes, I used generated folder  **_graph_labels to train and evaluate.

**Comment by yudezhi123456** [comment]
你好，最近我也在研究你的这个模型，可以在README中详细描述一下你的模型使用过程吗，这样看起来会比较方便

**Comment by weishu27** [comment]
可以查看doc文件夹里的论文pdf，描述详细些  (Please check paper for more details)

yudezhi123456 ***@***.***> 于2023年5月5日周五 11:17写道：

**Comment by yudezhi123456** [comment]
你好，我在运行训练脚本中出现当导入import experiment出现Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)的问题，我想可能是因为使用python版本的问题，请问您的python版本是多少？以及其他需要特别注意的版本可以指明一下吗？然后我继续按照requirements.txt进行安装。

**Comment by yudezhi123456** [comment]
> 你好，我在运行训练脚本中出现当导入import experiment出现Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)的问题，我想可能是因为使用python版本的问题，请问您的python版本是多少？以及其他需要特别注意的版本可以指明一下吗？然后我继续按照requirements.txt进行安装。

排查后发现是import torch_geometric导入的问题，想知道您用的torch版本以及cuda的版本是多少呢？

**Comment by yudezhi123456** [comment]
> 1.Just download public data;Simply move image and annotion separately to folder ‘images’ and 'annotations' . Or change input_path definition in .py as another choice. 2. /open-dataset/OD-layout/FUNSD_word_graph_labels/training_data is a save path,you can define it as you want.

您好，请问您是对funsd数据集中的json文件字段进行自行修改了吗？我并没有找到'img_data_list','text_coor','content'这些字段，希望您的解答，感谢！ （Hello, may I ask if you have made any modifications to the JSON file fields in the funsd dataset? I couldn't find the fields 'img_data_list', 'text_coor', and 'content'. I hope you can provide an answer, thank you.）

**Comment by weishu27** [comment]
> 
FUNSD 数据处理就用的原始label json文件，没有 用到'img_data_list','text_coor','content （The original label JSON file was used for processing the FUNSD dataset, and it did not include the fields 'img_data_list', 'text_coor', and 'content'.）
https://github.com/NormXU/Layout2Graph/blob/main/scripts/preprocess_data.py#L209

**Comment by yudezhi123456** [comment]
> > 
> 
> FUNSD 数据处理就用的原始label json文件，没有 用到'img_data_list','text_coor','content （The original label JSON file was used for processing the FUNSD dataset, and it did not include the fields 'img_data_list', 'text_coor', and 'content'.） https://github.com/NormXU/Layout2Graph/blob/main/scripts/preprocess_data.py#L209

十分感谢！重新拉取了代码问题解决了。但是存在一个问题可能是因为我下载安装包的版本问题，目前我用的是torch==1.10.0+cu102,torchvision==0.11.0+cu102以及torch_geometric==1.7.2。这个版本运行您的代码似乎有一些问题，想问一下您的版本是怎么样的。希望得到您的解答，感谢！

**Comment by NormXU** [comment]
> > > 
> > 
> > 
> > FUNSD 数据处理就用的原始label json文件，没有 用到'img_data_list','text_coor','content （The original label JSON file was used for processing the FUNSD dataset, and it did not include the fields 'img_data_list', 'text_coor', and 'content'.） https://github.com/NormXU/Layout2Graph/blob/main/scripts/preprocess_data.py#L209
> 
> 十分感谢！重新拉取了代码问题解决了。但是存在一个问题可能是因为我下载安装包的版本问题，目前我用的是torch==1.10.0+cu102,torchvision==0.11.0+cu102以及torch_geometric==1.7.2。这个版本运行您的代码似乎有一些问题，想问一下您的版本是怎么样的。希望得到您的解答，感谢！

Here is the dependency version we use:
```
torch==1.13.1+cu117
torchvision==0.14.1+cu117
torch-scatter==2.1.1
torch-sparse==0.6.17
torch-cluster==1.6.1
torch-spline-conv==1.2.2
```

and 

As for torch-geometric, you can simply use the latest version

**Comment by samakos** [comment]
hello again, hope this message finds you well. I have a question.
in the preprocess_data.py for doclaynet:
               for j, ocr_data in enumerate(all_ocr_data['cells']):
                        if ocr_data['bbox'][2] <= 0 or ocr_data['bbox'][3] <= 0:
                            continue
                       

is there a mistake? more specifically the all_ocr_data does not have cells. did you mean text_blocks maybe? but even I have text_blocks there is an error with the 'content'


what do you think? is there all_ocr_data['cells']? from where the key cells occur?

**Comment by weishu27** [comment]
> 

download from https://github.com/DS4SD/DocLayNet#extra-json-files

**Comment by Kastanas1** [comment]
@weishu27  Thank you very much, I also have a question.
I manage to do the train and in the end I get the best model. However I would like to know if the predictions of the model are saved. In the final evaluation that I get the f1 score, are the predictions of word labels being saved? If not, how can you get the predicted word_labels and convert to coco format?

**Comment by weishu27** [comment]
> @weishu27 Thank you very much, I also have a question. I manage to do the train and in the end I get the best model. However I would like to know if the predictions of the model are saved. In the final evaluation that I get the f1 score, are the predictions of word labels being saved? If not, how can you get the predicted word_labels and convert to coco format?

evaluate function only get F1 score,if you wanna coco result ,use predict function: https://github.com/NormXU/Layout2Graph/blob/main/experiment/gragh_layout_experiment.py#L32

**Comment by mohanhanmo** [comment]
Hello @weishu27, thank you very much and very nice work!

I have a question about the data preprocessing here. I am using the Doclaynet dataset. When running the training, the dataset was defined here, which includes keys of `img_data_list` or `text_coor`: https://github.com/NormXU/Layout2Graph/blob/f4d4642cbb3651eaec8b5c0e5beb7766190adb8c/mydatasets/gragh_net/layout_dataset.py#L24

However, the Doclaynet dataset has COCO format and there is no fields of `img_data_list` or `text_coor`. And I saw you mentioned in a previous answer that it may need some preprocessing from https://github.com/NormXU/Layout2Graph/blob/f4d4642cbb3651eaec8b5c0e5beb7766190adb8c/scripts/preprocess_data.py#L71

May I ask how I should do the data preprocessing and what would be the data structure like of the Doclaynet dataset? What else should I do in order to train on Doclaynet? Thank you!

**Comment by weishu27** [comment]
> 
1. Download the doclaynet dataset from public site
2. Run the preprocessing code  test_convert_DocLayNet_2_graph,after this, get data in format with 'img_data_list' and 'text_coor' 
3. Training with preprocessed data

**Comment by mohanhanmo** [comment]
Thank you so much for your quick response @weishu27 ! I was able to pre-process the Doclaynet dataset. But when I tried to train the model with Doclaynet, I met another issue:
```
File ~/Layout2Graph-main/networks/graph_net/graph_layout_net.py:208, in GraphLayoutNet.get_sampling(self, cell_boxes, targets, graphs, cnn_decode_feat, focal_loss_flag, device, linkings)
    205                 positive_cell_pair.append((i, j + i + 1))
    206 negative_cell_pair = list(set(pair_cell_list[index]).difference(set(positive_cell_pair)))
--> 208 assert len(set(positive_cell_pair).difference(set(pair_cell_list[index]))) == 0, "!!Lack of pair Set:{}".format(set(positive_cell_pair).difference(set(pair_cell_list[index])))
    209 positive_cell_pair = list(set(pair_cell_list[index]).intersection(set(positive_cell_pair)))
    210 if focal_loss_flag is False:

AssertionError: !!Lack of pair Set:
```

It seems like this assert error is because some pairs exist in `positive_cell_pair` but those pairs do not exist in `pair_cell_list[index]`. Then line 209 runs `positive_cell_pair = list(set(pair_cell_list[index]).intersection(set(positive_cell_pair)))`, in order to remove those pairs existing in `positive_cell_pair` but noting exist in `pair_cell_list[index]`.

Should I do anything to resolve this assert error, or should I ignore (comment out) line 208 since we would run 209 right after 208? I did not change any Doclaynet data downloaded. Thank you so much!

**Comment by weishu27** [comment]
> Thank you so much for your quick response @weishu27 ! I was able to pre-process the Doclaynet dataset. But when I tried to train the model with Doclaynet, I met another issue:
> 
> ```
> File ~/Layout2Graph-main/networks/graph_net/graph_layout_net.py:208, in GraphLayoutNet.get_sampling(self, cell_boxes, targets, graphs, cnn_decode_feat, focal_loss_flag, device, linkings)
>     205                 positive_cell_pair.append((i, j + i + 1))
>     206 negative_cell_pair = list(set(pair_cell_list[index]).difference(set(positive_cell_pair)))
> --> 208 assert len(set(positive_cell_pair).difference(set(pair_cell_list[index]))) == 0, "!!Lack of pair Set:{}".format(set(positive_cell_pair).difference(set(pair_cell_list[index])))
>     209 positive_cell_pair = list(set(pair_cell_list[index]).intersection(set(positive_cell_pair)))
>     210 if focal_loss_flag is False:
> 
> AssertionError: !!Lack of pair Set:
> ```
> 
> It seems like this assert error is because some pairs exist in `positive_cell_pair` but those pairs do not exist in `pair_cell_list[index]`. Then line 209 runs `positive_cell_pair = list(set(pair_cell_list[index]).intersection(set(positive_cell_pair)))`, in order to remove those pairs existing in `positive_cell_pair` but noting exist in `pair_cell_list[index]`.
> 
> Should I do anything to resolve this assert error, or should I ignore (comment out) line 208 since we would run 209 right after 208? I did not change any Doclaynet data downloaded. Thank you so much!

https://github.com/NormXU/Layout2Graph/issues/4#issuecomment-1650850903  You don't need to fix this error，it's just a warning for telling you that sampling edges are missing compared with all gt edges
