### ISSUE TITLE
错误询问

### ISSUE THREAD

**Issue by lhl2xju** [NormXU/Layout2Graph#4]
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/xxx/anaconda3/envs/t13/lib/python3.10/site-packages/torch_cluster/knn.py", line 72, in knn
        ptr_y = torch.bucketize(arange, batch_y)

    return torch.ops.torch_cluster.knn(x, y, ptr_x, ptr_y, k, cosine,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                       num_workers)
RuntimeError: Not compiled with CUDA support


您好！我遇到了这个问题，已经按照你给的依赖选项进行安装，但是仍然出现这个问题

**Comment by lhl2xju** [comment]
assert len(set(positive_cell_pair).difference(set(pair_cell_list[index]))) == 0, "!!Lack of pair Set:{}".format(set(positive_cell_pair).difference(set(p
air_cell_list[index])))
AssertionError: !!Lack of pair Set:{(xx, xx), ...}
我在复现代码时出现了以上的错误，阅读代码可知posi和nega应该是补集的关系，不知道我理解的对不对，望解答，非常感谢

**Comment by weishu27** [comment]
> ```
> assert len(set(positive_cell_pair).difference(set(pair_cell_list[index]))) == 0, "!!Lack of pair Set:{}".format(set(positive_cell_pair).difference(set(p
> ```
> 
> air_cell_list[index]))) AssertionError: !!Lack of pair Set:{(xx, xx), ...} 我在复现代码时出现了以上的错误，阅读代码可知posi和nega应该是补集的关系，不知道我理解的对不对，望解答，非常感谢

这里想做的是，判断构建的edges是否覆盖了gt的所有edges，打印出那些被漏掉的edge，看看是否关键。在我的实验中发现确实不能覆盖所有的edge，但是并不一定会影响最终结果，比如1、2、3同属一个instance，gt的edges为1&2，2&3，1&3，但是我们构建的edges只有1&2，2&3，缺失了1&3，这样最终的结果也是ok的。不知是否表达清楚，代码上确实不够合理，应该写成warning比较合适

**Comment by weishu27** [comment]
> RuntimeError: The following operation failed in the TorchScript interpreter. Traceback of TorchScript (most recent call last): File "/home/xxx/anaconda3/envs/t13/lib/python3.10/site-packages/torch_cluster/knn.py", line 72, in knn ptr_y = torch.bucketize(arange, batch_y)
> 
> ```
> return torch.ops.torch_cluster.knn(x, y, ptr_x, ptr_y, k, cosine,
>        ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
>                                    num_workers)
> ```
> 
> RuntimeError: Not compiled with CUDA support
> 
> 您好！我遇到了这个问题，已经按照你给的依赖选项进行安装，但是仍然出现这个问题

这看起来可能是安装的版本有问题，建议根据自己的环境配置，参照官方文档安装对应版本 https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html

**Comment by lhl2xju** [comment]
您好，您最近给的readme文件要求训练和推理在train/train_experiment.py，但是目前文档没有这个文件

**Comment by lhl2xju** [comment]
使用/mytools/train_graph.py运行代码时，提示需要transformers包，但是提示ERROR: Could not find a version that satisfies the requirement transfomers (from versions: none)                                                             
ERROR: No matching distribution found for transfomers 
下载的python版本为3.10，torch版本为2.0.1，环境为11.7

**Comment by NormXU** [comment]
1. The file should be named train_graph.py instead of train_experiment.py; it was a typo. Thank you for pointing it out.
2. requirements-dev.txt has been updated. Please pull the latest code or install transformers to ensure compatibility.

**Comment by lhl2xju** [comment]
Traceback (most recent call last):
  File "/home/code/Layout2Graph-main/train/train_graph.py", line 65, in <module>
    main(args)
  File "/home/code/Layout2Graph-main/train/train_graph.py", line 53, in main
    experiment_instance = getattr(experiment, get_experiment_name(args.experiment_name))(config)
  File "/home/dengqilin/code/Layout2Graph-main/experiment/graph_layout_experiment.py", line 30, in __init__
    super(GraphLayoutExperiment, self).__init__(config)
  File "/home/code/Layout2Graph-main/experiment/base_experiment.py", line 35, in __init__
    config = self._init_config(config)
  File "/home/code/Layout2Graph-main/experiment/graph_layout_experiment.py", line 212, in _init_config
    config['model']['num_classes'] = len(config['model']['class_list'])
KeyError: 'class_list'
其中printconfig['model']结果为{'type': 'resnet18', 'mixed_precision': 'no'}
是否代码还未整理好

**Comment by weishu27** [comment]
> Traceback (most recent call last): File "/home/code/Layout2Graph-main/train/train_graph.py", line 65, in main(args) File "/home/code/Layout2Graph-main/train/train_graph.py", line 53, in main experiment_instance = getattr(experiment, get_experiment_name(args.experiment_name))(config) File "/home/dengqilin/code/Layout2Graph-main/experiment/graph_layout_experiment.py", line 30, in **init** super(GraphLayoutExperiment, self).**init**(config) File "/home/code/Layout2Graph-main/experiment/base_experiment.py", line 35, in **init** config = self._init_config(config) File "/home/code/Layout2Graph-main/experiment/graph_layout_experiment.py", line 212, in _init_config config['model']['num_classes'] = len(config['model']['class_list']) KeyError: 'class_list' 其中printconfig['model']结果为{'type': 'resnet18', 'mixed_precision': 'no'} 是否代码还未整理好

每一个对应数据集的config里都有配置各自的class_list
